FROM nvidia/cuda:9.0-devel
MAINTAINER Leonardo Loures <luvres@hotmail.com>

RUN \
	cd \
	&& apt-get update \
	&& apt-get install -y git build-essential cmake libuv1-dev libmicrohttpd-dev \
  \
	&& git clone https://github.com/xmrig/xmrig-nvidia.git \
	&& cd xmrig-nvidia \
	&& cmake . \
	&& make -j$(nproc)
